@startuml

package SWAGroup12 {


    class EP_Board {
        -tiles
        -boardSize
        -tileSize
        -way
        -boardEventHandler
        -towerPlacementPopUp
        -towerPlacementPopUpSize
        +initialize()
        +boardEventHandler()
        +boardEventHandler(aHandler)
        +setTowerPlacementPopup(aPopup)
        +tiles() : Matrix
    }

    class EP_Tile {
        -twBorderColor
        -board
        -matrixLocation
        -occupied
        -locked
        +createTowerPlacementPopUp()
        +placeTower(aTower)
        +removeTower()
    }

    class EP_Enemy {
        -damage
        -health
        -speed
        -way
        -position
        -progress
        -tileProgress
        -distancePerStep
        -stepsPerTile
        -gameManager
        +initialize()
        +kill()
        +moveAlongPath()
    }

    class EP_BoardEventHandler {
        -manager
        -board
        +tileClicked(aTile)
    }

    class EP_EditorBEventHandler {
        +isNextToPrevious(aTile) : Boolean
        +isOnEdge(aTile) : Boolean
    }

    class EP_PlayBEventHandler {
    }

    class EP_TowerPlacementPopUp {
        -tile
        -board
        +initializeWith(aBoard, aTile)
        +placeTowerWithAsset(aAsset)
    }

    class EP_GameMode {
        -window
        -mainView
        -bottomView
        +switchTo(aModeClass)
        +takeOver(aArgs)
    }

    class EP_Menu {
        -manager
        +editorClicked()
        +playClicked()
        +quitClicked()
    }

    class EP_MenuMode {
        +initialize()
        +startEditor()
        +playGame()
    }

    class EP_PlayMode {
        -submode
        +takeOver(aArgs)
        +stopGame()
        +goToEditor()
    }

    class EP_EditorMode {
        -phase
        +initialize()
        +playMap()
        +takeOver(aArgs)
    }

    class EP_GameWindow {
        -mainView
        -bottomView
        +adjustSize()
        +openInWindow()
    }

    class EP_NotAGameManager {
        -way
        -map
        -money
        -lives
        +spawnEnemy()
    }

    EP_Board *--> EP_Tile
    EP_Board --> EP_BoardEventHandler
    EP_BoardEventHandler <|-- EP_EditorBEventHandler
    EP_BoardEventHandler <|-- EP_PlayBEventHandler
    EP_Board *--> EP_Enemy
    EP_Board --> EP_TowerPlacementPopUp
    EP_GameMode <|-- EP_MenuMode
    EP_GameMode <|-- EP_EditorMode
    EP_GameMode <|-- EP_PlayMode
    EP_MenuMode --> EP_Menu
    EP_GameMode --> EP_GameWindow
    EP_PlayMode --> EP_Board
    EP_EditorMode --> EP_Board
    EP_PlayMode ... EP_NotAGameManager
    EP_NotAGameManager *--> EP_Enemy
    EP_TowerPlacementPopUp --> EP_Tile
    EP_Tile --> EP_Board

}

@enduml
